global:
  scrape_interval: 15s
  #This scrape_interval tells Prometheus to always scrap the data every 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
	  #Prometheus can also scrape its own log

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          alias: "node_exporter"
		  #Grab data collected by Node Exporter

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          alias: "cadvisor"
		  #Grab data collected by CAdvisor
