apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  # User DB
  POSTGRES_DB: db-name
  # Db user
  POSTGRES_USER: db-username
  # Db password
  POSTGRES_PASSWORD: your-password
